### PR TITLE
Added version tagging for the dependencies

### PR DESCRIPTION
**Pull request by GoliathLabs**
It is a good idea to tag the versions of the used dependencies, as there may be some breaking changes in the future when a dependency receives an update.

### CODE REVIEW

**Comment by awlx** [comment]
@GoliathLabs please also add them in `setup.py` otherwise it's only half done :).

**Comment by GoliathLabs** [comment]
@awlnx Done

**Comment by awlx** [comment]
@GoliathLabs please run `black`

**Comment by GoliathLabs** [comment]
Thanks, done.

**Pull request merged**
